
# Syntax highlighting
markdown:            kramdown
highlighter:         rouge

# Setup
timezone:            US/Raleigh # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:				         Tale du Jour
title:               Tale du Jour
tagline:             'A collegiate view on traveling the world'
description:         'A collegiate view on traveling the world'
url:                 taledujour.com
rss:                 rss feed url
baseurl:             'taledujour.com/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                /assets/images/favicon.ico # /assets/img/icon.png [best 300px X 300px]
disqus:              taledujour # get it on https://disqus.com/admin/

author:
  name:           	 Brenna Milligan
  url:            	 about
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 4000

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
